apiVersion: v1
kind: Secret
metadata:
  name: reminderbot-secret
type: Opaque
stringData:
  TELEGRAM_TOKEN: "your-telegram-bot-token"
  POSTGRES_USER: "reminderbot"
  POSTGRES_PASSWORD: "your-password"
  POSTGRES_DB: "reminderbot"
  PGUSER: "reminderbot"
  PGPASSWORD: "your-password"
